### ISSUE TITLE
Producing a mesh with sharp edges

### ISSUE THREAD

**Issue by MaxMarschall** [ladybug-analysis-tools/butterfly#110]
Hello,

I have noticed that the mesh doesn't like to snap to edges.
![mesh](https://cloud.githubusercontent.com/assets/23235030/20266998/fad046f6-aa78-11e6-82d0-2b18e4977619.jpg)

So that geometry that is supposed to look like this...
![mesh2](https://cloud.githubusercontent.com/assets/23235030/20267016/10e66268-aa79-11e6-8441-df5720779116.png)

...turns out like this:
![mesh1](https://cloud.githubusercontent.com/assets/23235030/20267027/1828a59a-aa79-11e6-96eb-c02be81cec2d.png)

In the online PDF mentioned in the SHM component it looks like the mesh should fit the actual geometry better. Does this distort the simulation results and if so, how can I prevent it?

Cheers,
Max

**Comment by TheodoreGalanos** [comment]
Hi @MaxMarschall 

Meshing, as I've said, is a science of itself. You'll need a lot of trial and error to get  things going. Thankfully, you don't need to reinvent the wheel as almost everything we can think of has already been answered in www.cfd-online.com.

Even though you will get much better advice in the multiple threads about meshing in there I can offer some 'of the top of my head' advice:

- As always try gradually increasing the cell count and focus more cells on the surfaces (increase surface refinement)
- Use the explicit feature snap option of SHM (BF is by default using the implicit mode). You will need to extract the edges with the surfaceFeatureExtract utility of OF and then insert the .eMesh file into the features ( ) part of SHM. For this check the motorbike tutorial which is an **amazing example** of SHM meshing.
- Increase the smooth iterations in the snap ( ) part of SHM.

Be aware that there is a trade-off between fitting your geometry and quality. While better fitted surface might increase quality by decreasing skewness and other artifacts it can also increase it since (by definition) it increases non-orthogonality. 

To be abit more specific based on the image above:

Every time you mesh you need to ask yourself the same question: what am I trying to capture? If you are trying to capture the flow of wind passing through the geometry then you need to allow the cell size to adequately reflect the smallest detail you are targeting in your model. In this case I would allow at least 10 (maybe start with 5) cells spanning the minimum width of those passages. A simple division can then give you cell size which you can achieve by dividing your blockMesh cell size. Right now it feels like there's not more than 2 or 3 cells in the whole span of the openings.

I am sorry I don't have a better advice but meshing is really about trial and error. 

Good luck!

Kind regards,
Theodore.

**Comment by MaxMarschall** [comment]
Dear @TheodoreGalanos,

You're right, this is more of a ParaView question than a Butterfly question. Still many thanks for your detailed answer! I'll check it out and also consult the CFD forum.

Cheers,
Max

**Comment by saket411** [comment]
Hello everyone!!

I am trying to absorb the BF meshing parameters with trial and error at the moment.

I baked the SHM for a model I am working on, its a simple urbanscape on flat ground. The results look okay but the meshing appears to be hollow in some areas. Is it supposed to be like this?
![mesh perspective](https://cloud.githubusercontent.com/assets/1322619/21925148/16f28548-d9b7-11e6-976d-4abd44a67b73.PNG)
![mesh bottom view](https://cloud.githubusercontent.com/assets/1322619/21925149/16f5acdc-d9b7-11e6-8d48-c2f394e9b91d.PNG)

I read @**TheodoreGalanos** comment above suggesting increase in the smooth and solver iterations in the snap ( ) part of SHM. I cannot happen to find this feature. There is a snap in SHMDict but it accepts only bool.

Regards
Saket

**Comment by saket411** [comment]
Okay just to update the region inside the refinement zone is ...really refined and outside the box is not so good. This picture explains it all
![image](https://cloud.githubusercontent.com/assets/1322619/21928235/8d838b50-d9c4-11e6-90bc-d00aa383b8e9.png)
Left - Outside, Right - Inside

**Comment by mimarilker** [comment]
Actually, there has to be lots of things done as to meshing settings. I think there should be some additional options, hex mesh should be optional. I always prefer cartesian cutcell mesh, but being new to OF is very bad, so I dont know how to get finer, accurate mesh with OF. Please review the attached image.

![cartesiangrid350](https://cloud.githubusercontent.com/assets/22752273/21928750/421d29c0-d995-11e6-9bb1-8f15eec3b63c.jpg)

**Comment by saket411** [comment]
@**mimarilker** The equation is like alien language to me :P 

I saw the quality parameter in SHMDict. I hope it comes out soon. 
![image](https://cloud.githubusercontent.com/assets/1322619/21928903/7c4a4fc8-d9c8-11e6-9c96-84562d3f0a10.png)

**Comment by saket411** [comment]
Hi all,

In the previous image I have posted, comparison of inside and outside refinement... I am curious as to whether the triangular holes are actually 'holes' in the mesh and affect the results?

**Comment by mimarilker** [comment]
Hi @saket411 @maxmarschall I have tried everthing as to cell size surface refinement smooth tolerance and somver iterations and at the end I couldnt capture geometry accurately and I think theres sth wrong with this. Btw for Outdoor sample case I captured the geo with giving zero value to smooth and tolerance, but the mesh was castellated so it didnt work with curved or angled edges. So now I will try to explicit option and give feedback to you.

**Comment by mimarilker** [comment]
Hi @saket411 @maxmarschall I have tried everthing as to cell size surface refinement smooth tolerance and solver iterations and at the end I couldnt capture geometry accurately and I think theres sth wrong with this. Btw for Outdoor sample case I captured the geo with giving zero value to smooth and tolerance, but the mesh was castellated so it didnt work with curved or angled edges. So now I will try the explicit option and give feedback to you.

**Comment by saket411** [comment]
@**mimarilker** Thank you for your input. 
Just few basic questions,
1. Where can I change the smooth and tolerance parameters? I tried to find before as well but could not find it.
2. How does changing decomposition method from scotch to simple affect?
For next stage I want to integrate the contours in the urban model, I need to figure out the best settings with trial and error to mesh the contours in best possible way. Would be really helpful if you can give some advice on critical parameters to play with for meshing contours. 

Many Thanks!

**Comment by mimarilker** [comment]
Open snappyhexmeshdict.py and edit it, if rhino is open, then restart rhino.

**Comment by mimarilker** [comment]
@MaxMarschall @saket411 @mostaphaRoudsari 

I have tried to implement explicit feature option to capture edges more accurately, it gave perfect results: see the attached images.

![explicit feature](https://cloud.githubusercontent.com/assets/22752273/22121784/f567d38e-de8d-11e6-8d7d-ce19534a8439.JPG)

**Comment by MaxMarschall** [comment]
@mimarilker ,
You have quite a fine mesh there. Are you sure it still snaps nicely to the edges when you zoom in? When I was trying this, increasing the refinement generally made the edges finer but the mistake (if it IS a mistake) was still there at a smaller scale.

**Comment by mimarilker** [comment]
Yep, I ve checked everything, there's nothing wrong. As I said try to use explicit feature snap option, BF currently uses implicit one.

**Comment by TheodoreGalanos** [comment]
Hi everyone, sorry for not adding my thoughts earlier on this been quite busy with moving.

A few things that were mentioned:

1. Putting smoothing iterations to 0 will probably do exactly that, will not smooth. That means non-orthogonality will be small but your geometry will resemble the one of the castellated mesh. I've never tried it, since it is detrimental to mesh quality, but the result seems logical.

2. Explicit edge refinement is the old refinement mode of OF. It works, but it requires an .eMesh file to be created with the following command (an example, depending on geometry the angle can change but I'm not sure of optimal values):

`surfaceFeatureExtract -includedAngle 150 constant/triSurface/file.stl file150extraction`

This command creates a new folder with an .eMesh file in your trisurface folder (I believe). This file will identify edges, save them separately and allow you to refine them (if you want) by setting refinement levels in the following place in snappyHexMeshDict:

`    features		(
      file150extraction.eMesh levels (2 2);
 );`

The implicit feature edge method is the new method introduced somewhere around version 2.3.1. The implicit method does the above in an automatic way, using the `resolveFeatureAngle` key on the .stl file without the need to create an eMesh file. The reason you probably saw better quality then, if **all** other meshing settings were the same, is probably because mesh refinement didn't happen (!) since there was no .eMesh file available. This looks counter-intuitive I know. I think two possible causes is either the total cells number allowed is too small to properly refine the edges (smth that would be made visible in the refinement process stopping earlier if you were using the explicit method) or because the resolveFeatureAngle value is not ideal for the specific geometry. Try playing around with this value perhaps if the meshing isn't to time consuming. 

_I **highly** recommend reading meshing terminal output until you know how to follow and understand what is going on. They show a lot of information that can help you intuitively adjust your meshing settings._ 

3. The quality of the snapping process can be improved by playing with all the values of the snapControls block. The two that I play around the most are nSmoothPatch and nSolveIter. 

- nSolveIter is the number of interior smoothing iterations. This should be increased to a high number, I think we should change it as our default too, since it can increase quality with a very small computational impact. I usually put it at 300, which takes about 1 min in big meshes.
- nSmoothPatch is the number of pre-smoothing iterations. This makes quite a difference in meshing time. If you notice one of your SHM terminals, this is when the mesh is being iteratively smoothed after castellated mesh is finished. This is supposed to improve non-orthogonality but I've found that it is very sensitive to maxGlobalCell count and can actually introduce more errors as iterations increase. My max value to this would be 5, but the default is also fine.

4. I would not advise setting tolerance to 0. Tolerance is the **scaling factor** of the maximum length for attraction to the surface during snapping. Setting a scaling factor to 0 is like turning the snapping process off :)

As a final comment I highly recommend this presentation: https://openfoamwiki.net/images/f/f0/Final-AndrewJacksonSlidesOFW7.pdf. It goes quickly over all options in the snappyHexMesh dictionary and gives a summary of their role. It also identifies which options have greater or lesser impact to the meshing.

Hope all this helps!

Kind regards,
Theodore.

**Comment by mimarilker** [comment]
Thanks for the reply, I have experienced everything before you mentioned :) Altough it takes too much time, experience is invaluable. Btw as you said with implicit method currently available in BF, I couldnt get edge refinement. It rounds the corner of the geometry. e.g. when I change nsmoothpatch from 3 to 5, rounding angle at the corners increases. So I said theres sth wrong with this. I have really tried every option but no luck. Could you provide a working implicit feature snap sample in which all the edges of the geometry is captured?

Moreover, with explicit mode, edges captured perfectly, but I have manually extracted features from OF terminal manually and edit SHMdict to define eMesh file and to add and switch true explicit feature snap. The other difference was that I turned of implicit snap and multiregion snap. Except these everthing was exactly same.

**Comment by mimarilker** [comment]
I have seen such explanation on too many web sites.

- Geometries that can be perfectly discretized with blocks should not be snapped (deselect snap part in activation rows).
- Play on resolveFeatureAngle if you obtain high refinement zones in corner region.
- Snappy does not work very well on sharp edges

snap with low density mesh
![snap_fa95_](https://cloud.githubusercontent.com/assets/22752273/22138430/3aecb82e-dee9-11e6-9ac0-241c79a69bf0.png)



snap with high density mesh

![snap_fa95_tol01](https://cloud.githubusercontent.com/assets/22752273/22138442/5074b660-dee9-11e6-93f7-1fab459e4d25.png)

**Comment by TheodoreGalanos** [comment]
Than you had actually explicit edge running, if you had an eMesh created. What you can do to actually compare them properly is to use the same angle you used for the surfaceFeatureExtract in the resolveFeatureAngle parameter in SHMDict. 

It's nice actually, allows us to compare. According to the description in the OF manual itself, the implicit method is actually running a feature extraction on the .stl file so it really shouldn't be different. The only reasons I can think of is the angle parameter mentioned above and the levels allowed by SHM in the implicit method (which I'm not sure how they define).

nSmoothPatch increases the smoothing iterations so I believe it makes sense to smooth corners even more. However I had negative correlation with increasing the iterations in most of my models. I'm not so sure why, this part of SHM is a bit oblique to me.

As a general rule I think we need to focus on explicit method. The reason why we used implicit was mostly because it is automated and removes one extra step of preprocessing for the user. I think we can introduce explicit now so that users can choose if they wish too.

Finall, concerning examples, I don't really have since that is rarely an issue for most of my models (outdoor cases). Even for indoor cases, I would think I wouldn't worry a lot about rounded wall edgessince I don't feel they are as important as, let's say, the part of the room where the diffuser introduces the air (i.e. actual flow). 



Kind regards,
Theodore.

Kind regards,
Theodore.

**Comment by TheodoreGalanos** [comment]
Hi @mimarilker Yes I agree, I would use a simple blockMeshDict to actually mesh a simple room and the inlet/outlet if the damn thing isn't that hard to write. You can see some examples of custom blockMeshDicts for interior cases in OF tutorials. The scripts to generate one room is like 100 lines, that's crazy. 

I think I recall @mostaphaRoudsari mentioned somewhere that it might be possible to automate smth like that from BF to blockMeshDict, not sure though.

Kind regards,
Theodore.
Kind regards,
Theodore.

**Comment by mimarilker** [comment]
You re exactly right. Btw it takes too much time to mesh with explicit snap, also the soluiton consumes too much and didnt converge easily like in implicit one. I have written details from slack.

Someone can see the difference in the mesh with different feature snap options.

Exp. feature snap
![exp](https://cloud.githubusercontent.com/assets/22752273/22139483/f22c0ddc-deee-11e6-9783-790c036a7c6e.JPG)

Implcit feature snap
![imp](https://cloud.githubusercontent.com/assets/22752273/22139484/f2303a7e-deee-11e6-8d26-0fa36f73ac1a.JPG)

**Comment by mostaphaRoudsari** [comment]
@mimarilker is taking care of this: https://github.com/ladybug-analysis-tools/butterfly/pull/166

**Comment by mostaphaRoudsari** [comment]
This is a long conversation and not the best place to answer questions but to answer the most important ones you can update any value in butterfly dictionaries through `self.values`. For instance if you want to set implicit feature snap to false and the other one to true you can use the lines below:
```python
# assuming your case is called case
case.snappyHexMeshDict.values['snapControls']['explicitFeatureSnap'] = 'true' 
case.snappyHexMeshDict.values['snapControls']['implicitFeatureSnap'] = 'false'
case.snappyHexMeshDict.values['snapControls']['multiRegionFeatureSnap'] = 'false' 

# if the file is already saved then you have to overwrite the current file
case.snappyHexMeshDict.save(case.projectDir)
```
Also the missing faces is a limitation of Rhino in loading meshes with more than 4 vertices. Butterfly tries to break down meshes with more than 4 vertices into smaller pieces. Now that I'm thinking about it maybe we should just load the edges as polylines since this can give wrong information to users.

**Comment by mostaphaRoudsari** [comment]
see https://github.com/ladybug-analysis-tools/butterfly/issues/165#issuecomment-276473821

**Comment by mostaphaRoudsari** [comment]
Check this tutorial: https://sites.google.com/site/snappywiki/snappyhexmesh/cube-case

### Conclusion
- Geometries that can be perfectly discretized with blocks should not be snapped (deselect `snap` part in activation rows).
- Play on `resolveFeatureAngle` if you obtain high refinement zones in corner region.
- **Snappy does not work very well on sharp edges**
