### ISSUE TITLE
DynamoBIM and Autodesk CFD?

### ISSUE THREAD

**Issue by the-donn** [ladybug-analysis-tools/butterfly#130]
With DynamoBIM and Butterfly, have you given any thought to using Autodesk's own Simulation CFD? 

With the levels of detail option within Revit one can export natural ventilation models to their CFD product from Revit directly.

**Comment by TheodoreGalanos** [comment]
Hi @the-donn 

Personally I haven't given much thought to this. I will start working on Revit and testing these thigns out soon. Obviously BF for Dynamo can also be a very important tool giving an even more immediate access to CFD studies to the AEC industry, since Revit seems to be the mainstream program used.

The Revit to Rhino workflows I have worked with do not work well obviously so hopefully BF for Dynamo will help avoiding the work required to clean the model. I have heard however that Autodesk's CFD isn't efficient either but that is just hearsay since I haven't tried it. 

The main problem is getting a clean geometry. If there is an easy way within Revit to do that, e.g. leaving only structure by using filters perhaps, then BF can easily export that to a file that can be meshed through the OF pipeline. I feel atm Rhino is vastly superior for this, but this is biased due to my limited experience with Autodesk CFD pipeline. 

Another obstacle I feel is the proprietary nature of their CFD software. While I am guessing in the future it makes sense for BF to be able to link with it, I feel OF as an open source, heavily developed, and validated engine, feels as a superior alternative. At least until we prove that the internal pipeline works good and efficiently.

That's my 2c so far. Hopefully have more useful insight in the future.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
Hi @the-donn, Why do you need DynamoBIM for Autodesk CFD in the first place? Don't they already have a solid workflow?

Butterfly is built to create OpenFOAM cases and it's quite flexible to work with different geometry libraries but it won't work the other way since to connect the model to Autodesk CFD one has to re-write almost everything related to the CFD side. I just checked briefly and they have a Python API which you should be able to use to automate your tasks from within Dynamo.

I also changed the title to DynamoBIM and Autodesk CFD, which the answer to that is no. That will be a different plugin in my opinion.

**Comment by mostaphaRoudsari** [comment]
I'm going to close this as I think I answered the question. @the-donn feel free to re-open the issue if you think it's necessary.
