### ISSUE TITLE
CFD Help wanted

### ISSUE THREAD

**Issue by hdimor** [ladybug-analysis-tools/butterfly#134]
Hello all.

I am Starting Butterfly CFD Analysis.
In this case, I want to analysis Temperature and amount air flow speed in rooms that control with ducts.

I can't understand why my model doesn't work.  But I guess that problem is about 1. Boundary condition and 2. Meshing.

I tried many times to solving the problem, unfortunately, I could not solve them.

Can someone help me please?

Attachments:
https://www.dropbox.com/s/lxd4og4z2s7jkqr/OHMCFD%20Study2017.1.1s.gh?dl=0

Thanks-in-advance.

**Comment by TheodoreGalanos** [comment]
Hi @hdimor 

Thanks for testing BF. 

Can you give us some information on the nature of the issues you are facing? Is it an issue of convergence and results? Or is it an error that happens during case preparation?

I am currently away from working computers so I can't see the case right away. I'll take a look at it tomorrow and add my thoughts here.

Kind regards,
Theodore.

**Comment by hdimor** [comment]
Hi @TheodoreGalanos ,
Thank you so much for your prompt reply.
It runs with no error. However without get the results in this case.
It'll be great if you can see this Tomorrow.

Many thanks.

**Comment by DambronOlivier** [comment]
Hi @hdimor 

Interesting case.
It would be helpful that you illustrate the physical problem of this heat exchanger case.
After opening the gh Def I felt it was a bit messy around the boundary conditions whereas the preliminary resolution of your issue lies probably in a clear organisation of inlets and outlets and their respective temperatures.

I noticed the "jagged" component available in the example files plugged into meshset of createBfgeometry components are not there. Perhaps @mostaphaRoudsari could clarify on this.

**Comment by hdimor** [comment]
Hi @DambronOlivier ,
Thank you so much for your reply,
I run it again with jagged component, without any change. when we should use that?

Also I opened in para view, I see the problem in mesh.
![photo_2017-01-03_16-28-13](https://cloud.githubusercontent.com/assets/24868572/21608502/ca606f6a-d1b4-11e6-9872-d6d9f29cbddf.jpg)

Is could be solved with refinement Region mode ?

Hi @TheodoreGalanos , did you check the case?
Thanks a lot
Best regards.

**Comment by TheodoreGalanos** [comment]
Hi @hdimor 

I apologize didn't have time to see it today, I will check it tomorrow I promise.

From the mesh screenshot you provide I can see there are big problems in the meshing. Are those tubes supposed to be a closed or an open area (I assume open on the edges and not on top)?. Is the cube below a solid or hollow? If it is a solid you can try using one solid, i.e. subtract the tubes from the cube in Rhino, for the meshing. Should simplify the case bit. After that you can use a refinement region to improve the mesh in that region. A rectangle box starting below the cube and stretching above them should do well. 

Ofc using multiple stls is a bit more complicated but a lot more flexible. I would separate the case in minimum 3 stls:

- One stl for the 6 tubes

- One stl for the top surface of the cube, which the tubes intersect

- One stl for the rest of the cube.

First step would be to decrease the background mesh (e.g. half the size of blockMesh cells) while increasing your surface refinement levels so that your cells don't explode. Then you can increase the surface refinement of the top surface of the cube. I would set it at equal refinement as the tubes themselves. This should benefit the solution convergence as well. Then do a few mesh iterations, and see how changing the refinement levels changes the quality of the mesh.

I am sorry if it's a bit vague, not much I can do from a picture. I will give hopefully more useful insight tomorrow.

Kind regards,
Theodore.

**Comment by hdimor** [comment]
Hi @TheodoreGalanos ,
No worries and thank you.
Yes its hollow.
![photo_2017-01-04_06-15-26](https://cloud.githubusercontent.com/assets/24868572/21630319/ea1467b2-d227-11e6-98bd-ba499ac4c155.jpg)

I will check your suggestion.
Thanks again.
