### ISSUE TITLE
Upgrade to OpenFOAM v1612

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/butterfly#149]
Ideally this should not break the current workflows and the current version but if it is going to this is the right time to do so. I also hope they have made progress in making windows images for OpenFOAM.

**Comment by TheodoreGalanos** [comment]
Hi @mostaphaRoudsari 

The biggest change is the post-processing CLI. It might change a bit how we set up the post-processing components. As we discussed, it's actually a good change for us since they are somewhat structuring it like we did with BF, but it is a change nonetheless.

I'll try and install the new version and try it out. 

Kind regards,
Theodore.

**Comment by mimarilker** [comment]
wow! renewing the components for the new improvements of postprocessing would be very good @Theodore

**Comment by mostaphaRoudsari** [comment]
The basic workflow runs fine on my machine with the new version.

![image](https://cloud.githubusercontent.com/assets/2915573/21725975/a2f99b30-d408-11e6-9dde-6233d7e82ad5.png)

@TheodoreGalanos @mimarilker if you point out the most important ones we can implement them first. At the minimum we can address this issue #61 using the CLI.

**Comment by TheodoreGalanos** [comment]
Hello,

There is a big number of function objects (FOs) avaialable. I will try to separate this in their respective categories. Not sure if I should open a new issue or just type here. I'll do it here for now and if needed I transfer everything in a new post.

First category is the fields category. These function objects capture, calculate, or access information about fields (e.g. U, p, k, e, etc.) on various parts of the mesh. The most important fields FOs from my experience so far, that is the ones I use the most, are:

1. Field MinMax function object.

One of the simplest ones but probably my most used FO. I always enable this in my runs since I can very quickly and efficiently understand whethere my case is diverging and where exactly that happens. This FO reports the min and max values of the fields you provide and the location where these happen. The code is very simple (rsc here: https://develop.openfoam.com/Development/OpenFOAM-plus/blob/master/src/functionObjects/field/fieldMinMax/fieldMinMax.H):

` fieldMinMax1
    {
        type        fieldMinMax;
        libs        ("libfieldFunctionObjects.so");
        writeToFile yes;
        log         yes;
        location    yes;
        mode        magnitude;
        fields      (U p);
    }`

This example captures U and p, but k and epsilon can and should be used. Inputs are the fiels to give values for.

I can imagine using this function object in Honeybee a lot since users can really understand if something is going wrong. It should be pretty straightforward to plot this as well as it is quite lite, only 2 values for each parameter per iteration. If possible, a real-time, multi-graph output plotting (mainly) max values would be nice.

2.  Subtract

This one might be helpful for users that want to calculate a few things for their case.  It does what it says subtracting a field off another field. Main inputs are the two fields, others should be default (see: https://develop.openfoam.com/Development/OpenFOAM-plus/blob/master/src/functionObjects/field/subtract/subtract.H).

`Tdiff
    {
        type            subtract;
        libs            ("libfieldFunctionObjects.so");
        fields          (T Tmean);
        result          Tdiff;
        executeControl  writeTime;
        writeControl    writeTime;
    }`

3. Average value

This FO calculates the average value of other fields calculated through function objects that give singular values. The code example below calculates the average force coefficients, which are calculated by another function object (see: https://develop.openfoam.com/Development/OpenFOAM-plus/blob/master/src/functionObjects/field/valueAverage/valueAverage.H):

`valueAverage1
    {
        type        valueAverage;
        libs        ("libfieldFunctionObjects.so");
        writeToFile yes;
        log         yes;
        functionObject forceCoeffs1;
        fields      (Cm Cd Cl);
        window      0.5;
    }`

4. fluxSummary

This one is also very useful. It calculates the flux of u field across a selection of faces. The faces are selected through cellzones or even custom stl surfaces. Personally I use cellzones a lot for example when I want to monitor average velocities 1.1m above the floor or when I want to add porous zones in the mesh (i.e. trees). A very useful example implementation of this FO is to create a cellzone at the opening of your windows and then use the fluxSummary to get the (positive) flux of U passing through the cellzone or surface. The main inputs are the mode and the cellzone/surface to be used as the zone, and the direction depending on the mode.  

I must admit I haven't used this yet, I was doing workarounds before this FO, but it looks promising. Output is the mass flow over surface A. I will test and let you know. Code snippet below (see:https://develop.openfoam.com/Development/OpenFOAM-plus/blob/master/src/functionObjects/field/fluxSummary/fluxSummary.H).

`fluxSummary1
    {
        type        fluxSummary;
        libs        ("libfieldFunctionObjects.so");
        write       yes;
        log         yes;
        mode        cellZoneAndDirection;
        cellZoneAndDirection
        (
            (porosity (1 0 0))
        );
        scaleFactor 1.2;
    }`

5. wallShearStress

Some users have already been asking for this. Shear Stress is a measure of the force of friction from a fluid acting to a body (thing of air near the wall). It is given by the parallel forces on the wall. It is a simple FO with no real inputs (which calculates it for all walls in the model) or the specific wall boundary. Code snippet below (see: https://develop.openfoam.com/Development/OpenFOAM-plus/blob/master/src/functionObjects/field/wallShearStress/wallShearStress.H).

`    wallShearStress1
    {
        type        wallShearStress;
        libs        ("libfieldFunctionObjects.so");
        patches     (".*Wall");
    }`

6.  wallHeatFlux

Similar to above calculates the heat flux through a wall boundary. No inputs, unless user wants to specify specific wall boundary. Code snippet below (see: https://develop.openfoam.com/Development/OpenFOAM-plus/blob/master/src/functionObjects/field/wallHeatFlux/wallHeatFlux.H).

` wallHeatFlux1
    {
        type        wallHeatFlux;
        libs        ("libfieldFunctionObjects.so");
        patches     (".*Wall");
    }`

I think that's all for the field FOs. Of course with a component similar to the one you posted on #150 we can give users the possibility to literally input any FO they want or simply experiment.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment]
@TheodoreGalanos thank you for adding the new functions. It's too much data for a single issue. I think we need to break them down into several issues but I also need your help to understand how these new functionalities can be integrated into the current process.

**Comment by TheodoreGalanos** [comment]
@mostaphaRoudsari Ok I will seperate them into separate issues maybe.

We can have a discussion this week and talk about how each one integrates. Also maybe in relation to this #103

**Comment by TheodoreGalanos** [comment]
@mostaphaRoudsari Are we delaying this one after the BF release?

**Comment by TheodoreGalanos** [comment]
Function objects descriptions transfered to #177
