### ISSUE TITLE
Admin account needed to run BF since last update

### ISSUE THREAD

**Issue by MaxMarschall** [ladybug-analysis-tools/butterfly#157]
Dear @mostaphaRoudsari ,

I just updated Bf using the Butterfly component, and now the Create case from Geometries component gives me this message:
![untitled](https://cloud.githubusercontent.com/assets/23235030/21761276/2766f796-d652-11e6-9bfa-a80ef2064635.png)

I also notice that the "Last updated" date isn't today's date - is that normal?

Cheers,
Max

**Comment by mimarilker** [comment]
I have cleaned all the script and ghuser files related with BF and used installer.gh file to reinstall butterfly, than it begun to work. You may try this maybe, I think there is sth wrong with replacing older files during update which may stem from even admin. issues:(

**Comment by MaxMarschall** [comment]
Hi @mimarilker ,
I just restarted my PC, opened OF_Env, OF and Rhino all as administrator and it works.

**Comment by DambronOlivier** [comment]
After Updating butterfly its is necessary to close Gh and Rhino and reopen as Administrator.

**Comment by mimarilker** [comment]
So, the issue was solved than.

**Comment by MaxMarschall** [comment]
Yeah, good enough for me.

**Comment by mostaphaRoudsari** [comment]
As I mentioned in another discussion this exception doesn't have to do with OpenFOAM. I'm copying it here for the future reference:

`1. Solution exception:In order to run OpenFOAM using butterfly you must use an admin account or run the program as administrator.` has nothing to do with OpenFOAM installation. It simply checks to make see if you are running Rhino with an administrative account. Are you sure that you're running Rhino as an administrator? You need to right click on Rhino logo and then select run as administrator or follow [the above directions](https://github.com/ladybug-analysis-tools/butterfly/issues/142#issuecomment-270950371) to set it up to always run as administrator.

Here is the piece of code that you can use to test if you're an admin user:

```python
import ctypes
print ctypes.windll.shell32.IsUserAnAdmin()  # it returns 0 (not an admin) or 1 (admin)
```

**Comment by MaxMarschall** [comment]
Ah, good to know about that code.

I did start Rhino as you describe, only I never used to have to do it that way. Here is the full error message:
```
Runtime error (Exception): In order to run OpenFOAM using butterfly you must use an admin account or run the program as administrator.
Traceback:
  line 46, in __init__, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\runmanager.py"
  line 94, in __init__, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 236, in fromBFGeometries, "C:\Users\mma\AppData\Roaming\McNeel\Rhinoceros\5.0\scripts\butterfly\case.py"
  line 47, in script
```

Cheers,
Max

**Comment by mostaphaRoudsari** [comment]
Hi @MaxMarschall. I think you're confusing two different discussions. I asked the full error report for [this one](https://github.com/ladybug-analysis-tools/butterfly/issues/158#issuecomment-271277118). :)

**Comment by MaxMarschall** [comment]
Haha I did, sorry about that!
