### ISSUE TITLE
SHM vs Cartesian Cutcell mesh

### ISSUE THREAD

**Issue by mimarilker** [ladybug-analysis-tools/butterfly#164]
As we know there are some tiny problematic issues with SHM integration to BF, it is clear that mesh is mostly not uniform and aspect ratio is mostly too high eventhough the higher refinement levels. I have tried to set connection with Alta Dynamics Software on this issue, they have a standalone meshing module for cutcell mesh (http://altadyna.com/cfd/discretizer/). I have requested this module and waiting for their reply. I advise to improve mesh quality in a more appropriate way then the current SHM component. At first I am not sure about using too many external softwares for BF, however for mesh quality it is required.
As to SHM and Cutcell, you can see the difference in mesh uniformity and aspect ratio at the attached images below. Btw, I am not trying to say that SHM is not good for CFD purposes, I just want to open a discussion about its current usage in BF.

![solidw](https://cloud.githubusercontent.com/assets/22752273/21955881/cada4116-da7c-11e6-9f86-eb043afa8825.png)

![mesh](https://cloud.githubusercontent.com/assets/22752273/21955887/f5f54490-da7c-11e6-8614-997eaddc8a69.JPG)

**Comment by mimarilker** [comment]
I have made some additional researches on this issue and see that there are two different typical mesh refinement types named "volume refinement" and "surface based refinement". Actually with BF we are using vol.ref. as default, so I checked SHM dict pyhton file for additional features, however I couldnt find. So I advise to add a surface refinement option for meshing, it would be amazing!

**Comment by TheodoreGalanos** [comment]
Hi @mimarilker 

We have already implemented surface refinement, it is the refinementLevel input on the BF input geometries. We didn't separated it mostly because that's just about the extent of the options required in SHM (i.e. 2 integers for min-max ref. levels).

The main reason for high aspect ratios is not really SHM, at least not in these simple examples. As I've said a few times in this forum meshing is an art in itself, much more difficult than using OF to solve. The reason for high aspect ratios in these examples is user settings. There is a way to control this, you do it by knowing what your base mesh cell size is, what each refinement level means for the cell size, how you assign different refinement levels to different areas, how many refinement levels do you allow between different areas, etc.

It's a lot of work with a lot of trial and error. I don't have a lot of experience and access to propriatory meshing software so I can't be certain if they emply an automatic process for meshing that gives satisfactory results. I feel smth like that would be close to impossible given the range of different cases, it really just boils down to A LOT of trial and error. 

I think the best initial resource we could probably share is these guidelines which in the meshing part covers a lot of the central meshing issues for urban wind simulations, which also allows users to research deeper in these areas if they wish to. Perhaps I could start a wiki on meshing guidelines or tips when I get a bit of free time. Although I feel I would do much worse job than the numerous expert posts in cfd-online.

http://theairshed.com/pdf/COST%20732%20Best%20Practice%20Guideline%20May%202007.pdf

Kind regards,
Theodore.
