### ISSUE TITLE
Automate the process of creating 2D simulation by adding a plane to case/blockMesh

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-analysis-tools/butterfly#76]
@TheodoreGalanos I will leave implement this one with the new style blockMeshDict.

**Comment by mostaphaRoudsari** [comment]
here is an example: https://github.com/OpenFOAM/OpenFOAM-3.0.x/tree/master/tutorials/incompressible/simpleFoam/mixerVessel2D

**Comment by mostaphaRoudsari** [comment]
A couple of more tests and this is done!
![image](https://cloud.githubusercontent.com/assets/2915573/21852309/8fbdb9c6-d7e0-11e6-9447-9ffeea39b65a.png)

**Comment by Zarisu** [comment]
Hey @mostaphaRoudsari, sorry to trouble you, but I can't get my script to run after the last update because of a runtime error caused by 'make2dParameters'. I simply dunno how to solve it or how to bypass it, hope you can help :)    
![question_make2dparameters](https://cloud.githubusercontent.com/assets/23387793/22198391/a2a48b26-e156-11e6-8080-5769dcf6902f.PNG)

Best Regards
/Toke

**Comment by mostaphaRoudsari** [comment]
Hi @Zarisu , This is a change in the API. If everything is updated on your machine correctly then restarting Rhino should solve the problem. The libraries need to be reloaded.

**Comment by mostaphaRoudsari** [comment]
Also this is already implemented! The indoor analysis doesn't converge which @TheodoreGalanos is trying to figure out.

**Comment by TheodoreGalanos** [comment]
@mostaphaRoudsari Indoor case is ok now. Solution is to refine the mesh only using blockMesh initial cells and not snappyhexmesh as it usually creates new cells and nasty things happen.
